export const SET_ADMIN = 'SET_ADMIN';
export const SET_ADMIN_GET_REQUEST_LOADING = 'SET_ADMIN_GET_REQUEST_LOADING';
export const SET_ADMIN_GET_REQUEST_SUCCESS = 'SET_ADMIN_GET_REQUEST_SUCCESS';
export const SET_ADMIN_GET_REQUEST_ERROR = 'SET_ADMIN_GET_REQUEST_ERROR';
export const RESET_STORE = 'RESET_STORE';