export const SET_CONTACT = 'SET_CONTACT';
export const SET_CONTACT_DELETE_REQUEST_LOADING = 'SET_CONTACT_DELETE_REQUEST_LOADING';
export const SET_CONTACT_DELETE_REQUEST_SUCCESS = 'SET_CONTACT_DELETE_REQUEST_SUCCESS';
export const SET_CONTACT_DELETE_REQUEST_ERROR = 'SET_CONTACT_DELETE_REQUEST_ERROR';

export const SET_CONTACT_POST_REQUEST_LOADING = 'SET_CONTACT_POST_REQUEST_LOADING';
export const SET_CONTACT_POST_REQUEST_SUCCESS = 'SET_CONTACT_POST_REQUEST_SUCCESS';
export const SET_CONTACT_POST_REQUEST_ERROR = 'SET_CONTACT_POST_REQUEST_ERROR';

export const RESET_STORE = 'RESET_STORE';