export const SET_USER = 'SET_USER';
export const SET_USER_GET_REQUEST_LOADING = 'SET_USER_GET_REQUEST_LOADING';
export const SET_USER_GET_REQUEST_SUCCESS = 'SET_USER_GET_REQUEST_SUCCESS';
export const SET_USER_GET_REQUEST_ERROR = 'SET_USER_GET_REQUEST_ERROR';
export const RESET_STORE = 'RESET_STORE';